### ISSUE TITLE
M10-B not recognized on Ubuntu 17.10

### ISSUE THREAD

**Issue by hstehr** [olivia/via-config#30]
I'm following the instructions on https://rama.works/m10b-via-firmware-update-01:
- flashed "rama_m10_b_default.hex" to M10-B using dfu-programmer
- installed via-config_0.2.7_amd64.deb on Ubuntu 17.10
- when running via-config, I get an animation screen with X's and O's but M10-B is not recognized
- Device shows up in lsusb as "Bus 001 Device 079: ID 5241:00ab" and sends key strokes

Any help is appreciated!

**Comment by Wilba6582** [comment]
Can you try connecting the M10-B directly to the PC, not through a hub?

Can you check there are no other "keyboard" devices also connected which might be confusing VIA Configurator?

**Comment by hstehr** [comment]
Tried different USB ports, directly on the box. All USB devices except M10 and main keyboard un-plugged (I need at least one keyboard or mouse). Same result. For further testing, does the M10 need to be connected before starting via-config or will it auto-detect newly connected devices? Is there a debug mode or log file where I could see the communication? Anything else worth trying? Thanks!

**Comment by hstehr** [comment]
Unfortunately, it still did not work for me. But I was able to program the M10-B using the QMK Configurator. In case someone is having similar problems on Linux, here are a few tips:
- The M10-B uses the DFU bootloader and _dfu-programmer_ can be used to flash firmware files:
  - Download and install from http://dfu-programmer.github.io
  - _libusb-1.0-0-dev_ needs to be installed (using apt-get) before compiling dfu-programmer
  - To flash, follow the commands shown in the screenshot at https://rama.works/m10b-via-firmware-update-01
- To install via-config from the .deb package, _libappindicator1_ needs to be installed previously:
  - sudo apt-get install libappindicator1
  - sudo dpkg -i via-config_0.2.7_amd64.deb
- If trying to run via-config with sudo gives an error "No protocol specified", there are two possible workarounds:
  - log out and re-login in X11 mode (select X11 in the settings menu when choosing the login user)
  - OR, in a terminal, type: `xhost si:localuser:root`
- If via-config still does not recognize the M-10B, the QMK Configurator can be used to create a keymap and compile a firmware:
  - Go to https://config.qmk.fm/#/rama/m10_b/LAYOUT
  - Flash the firmware using dfu-programmer like above
