### ISSUE TITLE
M60-A does not work in BIOS

### ISSUE THREAD

**Issue by graphis** [olivia/via-config#36]
Would be good to have the M60-A working also in BIOS.

**Comment by Wilba6582** [comment]
It works for me in my BIOS. Maybe try turning on/off the NKRO using the "Toggle NKRO" keycode. You can see whether NKRO is enabled by using EK Switch Hitter or some other program that tests keyboards.

**Comment by graphis** [comment]
I tried that.

The problem is that the keyboard sometimes works in BIOS sometimes not. Also the keyboard shortcut which I use for shutting down my hackintos (control  + eject, aka control + fn2 + f) is also functioning randomly. I thought it is a keboard issue. On my other keyboard / these shortcuts are working. At the same time on the M60-A the same shortcuts are failing.

**Comment by Wilba6582** [comment]
Technically this is a QMK firmware issue. VIA Configurator is just the front end to configure the QMK firmware. I suggest you raise an issue in the QMK firmware github where it will get more visibility from people who have more experience with QMK, OSX, and the messy details of keyboard firmware.

**Comment by graphis** [comment]
Ok then, I got the cause of this error. NKRO gets randomly acivated. Is there a way to disable NKRO when compiling te hex file?

**Comment by Wilba6582** [comment]
It shouldn't be random. "Toggle NKRO" will change the NKRO mode on/off, and this gets saved to EEPROM so the mode persists if the keyboard is powered off and on.
