### ISSUE TITLE
Indicator LED and TO()

### ISSUE THREAD

**Issue by holtenc** [olivia/via-config#41]
I use the following to activate an LED while on a specific layer: 

`uint32_t layer_state_set_user(uint32_t state)
{
    if (biton32(state) == 2) {
        PORTC |= (1<<6);
	} else {
		PORTC &= ~(1<<6);
    }
    return state;
}`

Which functions correctly with `MO()` and `TG()`. Not so with `TO()`. FWIW it works as intended without all the Via magic.

**Comment by holtenc** [comment]
are you referring to this?
```
void matrix_init_user(void) {
  // set CapsLock LED to output and low
  DDRC |= (1 << 6);
  PORTC &= ~(1 << 6);
  // set NumLock LED to output and low
  DDRB |= (1 << 6);
  PORTB &= ~(1 << 6);
  // set ScrollLock LED to output and low
  DDRB |= (1 << 5);
  PORTB &= ~(1 << 5);
}
```

**Comment by Wilba6582** [comment]
Yeah, sorry, that doesn't explain why it works some of the time.

**Comment by holtenc** [comment]
sorry I didn't realize how much work was left to be done on Via. (just read your exchange with drashna and discord comments). This layer indicator issue now seems very insignificant. Feel free to delete this and I'll refrain from doing a PR to both Via and QMK to add support for the board I'm working on until you guys feel like it's a good time to do so.

**Comment by Wilba6582** [comment]
No, all bugs should be logged as issues, it's still something that needs to be fixed, and sometimes dealing with one bug fixes other potential ones.

**Comment by Wilba6582** [comment]
Fixed
