### ISSUE TITLE
VIA will not detect PCB after being flashed with QMK

### ISSUE THREAD

**Issue by trinity1561** [olivia/via-config#61]
I'm not sure if I'm doing something wrong, but I have 2 VIA supported PCB and they are both having this issue where I would flash the PCB using QMK (because I wanted to map LT(layer, kc)) but when I try to plug it back into VIA, it will show the loading bar, but never load.

My first VIA board, Instant60, I was able to reset the EEPROM to make VIA see it again, but with my 2nd VIA board (XENO, WT75-a), it will not let me reset EEPROM.  I would get a [Memory write error](https://cdn.discordapp.com/attachments/537514291440517121/610325205906096128/unknown.png).  Is there something that needs to be done to get QMK flashed PCB to be detected by VIA without having to reset EEPROM?

**Comment by Wilba6582** [comment]
VIA does not require the EEPROM to be reset to function, resetting the EEPROM after flashing with new firmware only causes the keymaps in EEPROM to be reloaded with the default keymap that is in the firmware (i.e. what you changed in your keymap.c).

Most likely the problem you are having is related to building without the features that VIA requires, which are raw HID and dynamic keymaps. These features are enabled in the "via" keymap folder but not the "default" keymap folder. Perhaps you have changed the keymap.c in the "default" keymap folder (or copied that as the base for your own). So look in rules.mk and make sure QMK is compiling the features that VIA requires.

**Comment by trinity1561** [comment]
OK that makes sense.  I got it working now.  I was not aware that there is a different keymap folder for VIA.  Thanks for your help!
