### ISSUE TITLE
Latest Version won't work on OSX with my m60-a

### ISSUE THREAD

**Issue by scotttarlow** [olivia/via-config#62]
I just upgraded to the newest version and I'm stuck on the loading screen... wondering if this is a wide spread issue.

**Comment by scotttarlow** [comment]
Just to update - 0.3.6 works without a hitch.

**Comment by ValdisThomann** [comment]
Thanks for the heads up! Developing a fix, will update when it's released.

**Comment by ValdisThomann** [comment]
Hey mate, should be fixed now: https://github.com/olivia/via-config/releases/tag/v0.4.1

You'll need to update your firmware if you want to use macros though.
